# 파일 규격 버전 -> '3'을 기입하면 최신 버전 사용한다는 의미
version: '3.3'
services:
  fastapi:
    image: fastapi
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - 8000:8001
    volumes:
      - ./app:./app






